export type SidebarItem = {
  num: number;
  label: string;
  href: string;
  icon: string;
  roles: string[];
};

export const sidebarMenuItems: SidebarItem[] = [
  {
    num: 1,
    label: "Dashboard",
    href: "/admin",
    icon: "🏠",
    roles: ["admin"],
  },
  {
    num: 2,
    label: "Dashboard",
    href: "/enseignant",
    icon: "🏠",
    roles: ["prof"],
  },
  {
    num: 3,
    label: "Dashboard",
    href: "/eleve",
    icon: "🏠",
    roles: ["eleve"],
  },

  {
    num: 4,
    label: "Matières",
    href: "/admin/matieres",
    icon: "📚",
    roles: ["admin"],
  },
  {
    num: 5,
    label: "Enseignants",
    href: "/admin/enseignants",
    icon: "👨‍🏫",
    roles: ["admin"],
  },
  {
    num: 6,
    label: "Répartitions",
    href: "/admin/repartitions",
    icon: "📅",
    roles: ["admin"],
  },
  {
    num: 7,
    label: "Emploi du temps",
    href: "/enseignant/emploi_du_temps",
    icon: "🕐",
    roles: ["prof"],
  },
  {
    num: 8,
    label: "Répartitions",
    href: "/enseignant/repartitions",
    icon: "📅",
    roles: ["prof"],
  },
  {
    num: 9,
    label: "Classes",
    href: "/admin/classes",
    icon: "🏫",
    roles: ["admin"],
  },
  {
    num: 10,
    label: "Mes classes",
    href: "/enseignant/classes",
    icon: "🏫",
    roles: ["prof"],
  },
  {
    num: 11,
    label: "Emploi du temps",
    href: "/eleve/emploi_du_temps",
    icon: "🕐",
    roles: ["eleve"],
  },
  {
    num: 12,
    label: "Élèves",
    href: "/admin/eleves",
    icon: "🎒",
    roles: ["admin"],
  },
  {
    num: 13,
    label: "Élèves",
    href: "/enseignant/eleves",
    icon: "🎒",
    roles: ["prof"],
  },
  {
    num: 14,
    label: "Utilisateurs",
    href: "/admin/users",
    icon: "👤",
    roles: ["admin"],
  },
  {
    num: 15,
    label: "Leçons",
    href: "/enseignant/lecons",
    icon: "📖",
    roles: ["prof"],
  },
  {
    num: 16,
    label: "Leçon en image",
    href: "/enseignant/lecon-image",
    icon: "🖼️",
    roles: ["prof"],
  },
  {
    num: 17,
    label: "Leçon en image",
    href: "/eleve/lecon-image",
    icon: "🖼️",
    roles: ["eleve"],
  },
  {
    num: 18,
    label: "Exercices",
    href: "/enseignant/exercices",
    icon: "✏️",
    roles: ["prof"],
  },
  {
    num: 19,
    label: "Exercices",
    href: "/eleve/exercices",
    icon: "✏️",
    roles: ["eleve"],
  },
  {
    num: 20,
    label: "Notes",
    href: "/enseignant/notes",
    icon: "📝",
    roles: ["prof"],
  },
  {
    num: 21,
    label: "Mes notes",
    href: "/eleve/notes",
    icon: "📝",
    roles: ["eleve"],
  },
  {
    num: 22,
    label: "Médias",
    href: "/enseignant/medias",
    icon: "🎬",
    roles: ["prof"],
  },
  {
    num: 23,
    label: "Médias",
    href: "/eleve/medias",
    icon: "🎬",
    roles: ["eleve"],
  },
  {
    num: 24,
    label: "Code",
    href: "/enseignant/code",
    icon: "</>",
    roles: ["prof"],
  },
  {
    num: 25,
    label: "Code",
    href: "/eleve/code",
    icon: "</>",
    roles: ["eleve"],
  },
  {
    num: 26,
    label: "Quiz",
    href: "/enseignant/quiz",
    icon: "❓",
    roles: ["prof"],
  },
  {
    num: 27,
    label: "Quiz",
    href: "/eleve/quiz",
    icon: "❓",
    roles: ["eleve"],
  },
];
